export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_OTP_REQUEST = "USER_OTP_REQUEST";
export const USER_OTP_SUCCESS = "USER_OTP_SUCCESS";
export const USER_OTP_FAILURE = "USER_OTP_FAIL";
export const USER_OTP_RESET = "USER_OTP_RESET";

export const USER_OTP_VALID = "USER_OTP_VALID";
export const USER_OTP_INVALID = "USER_OTP_INVALID";

export const USER_FORGOT_PASS = "USER_FORGOT_PASS";
export const USER_FORGOT_PASS_INVALID = "USER_FORGOT_PASS_INVALID";

export const USER_RESET_PASS = "USER_RESET_PASS";
export const USER_RESET_PASS_INVALID = "USER_RESET_PASS_INVALID";
